-- MinTech Ethiopia — historical daily operations reports.
-- GENERATED by scripts/generate-ops-seed.mjs — do not edit by hand.
-- Paste into the Supabase SQL editor and Run. Safe to re-run: each day
-- upserts on date_label, exactly like the Telegram bot's ingest does.
-- 62 day-entries, 31/3/2026 → 1/7/2026

begin;

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '31/3/2026', '2026-03-31T00:00:00.000Z', 'historical import',
  '{"ETL9":30,"5EL":11,"2EL":20,"3EL":17,"EC15":5}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '1/4/2026', '2026-04-01T00:00:00.000Z', 'historical import',
  '{"ETL15":1,"ETL9":39,"2EL":50.5,"3EL":4}'::jsonb, '{"ETL9":29,"2EL":30.875}'::jsonb, '{"ETL15":25.8,"ETL9":59.64,"ETL6":1.88,"5EL":80.47,"2EL":214.45,"3EL":295.9,"EC15":366.25,"EC90":167.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":32500,"Beige":5500},"kg40":{"Beige":63707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '2/4/2026', '2026-04-02T00:00:00.000Z', 'historical import',
  '{"ETL15":0.52,"ETL9":25,"2EL":120}'::jsonb, '{"ETL9":44,"2EL":39}'::jsonb, '{"ETL15":24.8,"ETL9":64.64,"ETL6":1.88,"5EL":80.47,"2EL":202.95,"3EL":291.9,"EC15":366.25,"EC90":167.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":29500,"Beige":5500},"kg40":{"Beige":63707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '3/4/2026', '2026-04-03T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":33.6,"2EL":28.6}'::jsonb, '{"ETL15":24.28,"ETL9":73.24,"ETL6":1.88,"5EL":80.47,"2EL":111.55,"3EL":291.9,"EC15":366.25,"EC90":167.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":29500,"Beige":5500},"kg40":{"Beige":60707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '6/4/2026', '2026-04-06T00:00:00.000Z', 'historical import',
  '{"ETL15":20,"ETL9":22,"2EL":0.85,"EC90":19}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '7/4/2026', '2026-04-07T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":17.56,"2EL":19.25}'::jsonb, '{"ETL15":4.28,"ETL9":72.4,"ETL6":1.88,"5EL":65.47,"2EL":138.65,"3EL":269.4,"EC15":366.25,"EC90":103.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":24500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '8/4/2026', '2026-04-08T00:00:00.000Z', 'historical import',
  '{"ETL9":36,"2EL":45,"3EL":20,"EC90":10}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '9/4/2026', '2026-04-09T00:00:00.000Z', 'historical import',
  '{"ETL9":38,"2EL":61,"EC15":1,"EC90":6}'::jsonb, '{"ETL9":17.92,"2EL":16.625}'::jsonb, '{"ETL15":4.28,"ETL9":63.92,"ETL6":1.88,"5EL":65.47,"2EL":130.025,"3EL":229.4,"EC15":366.25,"EC90":57.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":24500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '10/4/2026', '2026-04-10T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":18.6,"2EL":17.5}'::jsonb, '{"ETL15":4.28,"ETL9":44.52,"ETL6":1.88,"5EL":65.47,"2EL":86.375,"3EL":229.4,"EC15":365.25,"EC90":51.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":24500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '11/4/2026', '2026-04-11T00:00:00.000Z', 'historical import',
  '{"ETL9":30,"5EL":38,"2EL":60,"EC15":5}'::jsonb, '{}'::jsonb, '{"ETL15":4.28,"ETL9":44.52,"ETL6":1.88,"5EL":65.47,"2EL":86.375,"3EL":229.4,"EC15":365.25,"EC90":51.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":24500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '12/4/2026', '2026-04-12T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":16.28,"2EL":14.125}'::jsonb, '{"ETL15":4.28,"ETL9":30.8,"ETL6":1.88,"5EL":27.47,"2EL":40.65,"3EL":229.4,"EC15":360.25,"EC90":51.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":22500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '13-14/4/2026', '2026-04-13T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{}'::jsonb, '{"ETL15":4.28,"ETL9":30.8,"ETL6":1.88,"5EL":27.47,"2EL":40.65,"3EL":229.4,"EC15":360.25,"EC90":51.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":22500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '14/4/2026', '2026-04-14T00:00:00.000Z', 'historical import',
  '{"ETL9":20,"2EL":10,"EC15":5}'::jsonb, '{}'::jsonb, '{}'::jsonb, '{}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '15/4/2026', '2026-04-15T00:00:00.000Z', 'historical import',
  '{"ETL9":17.52,"2EL":5,"3EL":5,"EC15":25,"EC90":2.52}'::jsonb, '{"ETL9":12.96,"2EL":15.375}'::jsonb, '{"ETL15":4.28,"ETL9":23.76,"ETL6":1.88,"5EL":27.47,"2EL":46.025,"3EL":229.4,"EC15":355.25,"EC90":51.24,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":22500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '16/4/2026', '2026-04-16T00:00:00.000Z', 'historical import',
  '{"ETL9":24,"2EL":30,"3EL":46,"EC15":5,"EC90":1}'::jsonb, '{"ETL9":21.8,"2EL":8.225}'::jsonb, '{"ETL15":4.28,"ETL9":28.04,"ETL6":1.88,"5EL":27.47,"2EL":49.25,"3EL":224.4,"EC15":330.25,"EC90":48.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":22500,"Beige":5500},"kg40":{"Beige":57707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '17/4/2026', '2026-04-17T00:00:00.000Z', 'historical import',
  '{"ETL15":2,"ETL9":18,"5EL":5,"2EL":21,"3EL":42}'::jsonb, '{"ETL9":23.8,"2EL":13.25}'::jsonb, '{"ETL15":4.28,"ETL9":27.84,"ETL6":1.88,"5EL":27.47,"2EL":32.5,"3EL":178.4,"EC15":325.25,"EC90":47.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":20500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '18/4/2026', '2026-04-18T00:00:00.000Z', 'historical import',
  '{"ETL9":4,"5EL":22,"EC15":10.7,"EC90":2}'::jsonb, '{"ETL9":6.2,"2EL":4.2}'::jsonb, '{"ETL15":2.28,"ETL9":16.04,"ETL6":1.88,"5EL":22.47,"2EL":15.7,"3EL":136.4,"EC15":325.25,"EC90":47.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":20500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '19/4/2026', '2026-04-19T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL15":18.72,"ETL9":29.8,"2EL":12.9}'::jsonb, '{"ETL15":21,"ETL9":41.84,"ETL6":1.88,"5EL":0.47,"2EL":28.6,"3EL":136.4,"EC15":314.55,"EC90":45.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":20500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '20/4/2026', '2026-04-20T00:00:00.000Z', 'historical import',
  '{"ETL15":20,"ETL9":24,"2EL":1,"3EL":6,"EC90":1}'::jsonb, '{}'::jsonb, '{"ETL15":21,"ETL9":41.84,"ETL6":1.88,"5EL":0.47,"2EL":28.6,"3EL":136.4,"EC15":314.55,"EC90":45.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":20500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '21/4/2026', '2026-04-21T00:00:00.000Z', 'historical import',
  '{"ETL9":15,"2EL":20,"EC15":25}'::jsonb, '{"ETL15":6.6,"ETL9":26.92}'::jsonb, '{"ETL15":7.6,"ETL9":44.76,"ETL6":1.88,"5EL":0.47,"2EL":27.6,"3EL":130.4,"EC15":314.55,"EC90":44.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":20500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '22/4/2026', '2026-04-22T00:00:00.000Z', 'historical import',
  '{"ETL9":14.72,"3EL":1,"EC15":5,"EC90":10}'::jsonb, '{"ETL9":4.36}'::jsonb, '{"ETL15":7.6,"ETL9":44.12,"ETL6":1.88,"5EL":0.47,"2EL":7.6,"3EL":130.4,"EC15":289.55,"EC90":44.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":20500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '23/4/2026', '2026-04-23T00:00:00.000Z', 'historical import',
  '{"ETL15":5,"ETL9":10.52,"ETL6":5,"5EL":2,"2EL":25,"3EL":14,"EC90":0.52}'::jsonb, '{"ETL9":10.2,"ETL6":6.2,"5EL":4.4,"2EL":25.75}'::jsonb, '{"ETL15":7.6,"ETL9":29.6,"ETL6":8.08,"5EL":4.87,"2EL":33.35,"3EL":129.4,"EC15":284.55,"EC90":34.72,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":20500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":46000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '24/4/2026', '2026-04-24T00:00:00.000Z', 'historical import',
  '{"3EL":0.85}'::jsonb, '{"ETL9":1.6,"5EL":2.05,"2EL":4.55}'::jsonb, '{"ETL15":2.6,"ETL9":20.68,"ETL6":3.08,"5EL":4.92,"2EL":12.9,"3EL":115.4,"EC15":284.55,"EC90":34.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":45000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '25/4/2026', '2026-04-25T00:00:00.000Z', 'historical import',
  '{"ETL15":25,"ETL9":10,"5EL":5}'::jsonb, '{"ETL15":30.12,"ETL9":10,"5EL":8.85,"2EL":12.775}'::jsonb, '{"ETL15":32.72,"ETL9":30.68,"ETL6":3.08,"5EL":13.77,"2EL":25.675,"3EL":114.55,"EC15":284.55,"EC90":34.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":45000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '26/4/2026', '2026-04-26T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL15":29.36,"ETL9":5.84,"5EL":5.5}'::jsonb, '{"ETL15":37.08,"ETL9":26.52,"ETL6":3.08,"5EL":14.27,"2EL":25.675,"3EL":114.55,"EC15":284.55,"EC90":34.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":43000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '27/4/2026', '2026-04-27T00:00:00.000Z', 'historical import',
  '{"ETL15":20,"ETL9":24,"5EL":1,"2EL":2,"3EL":5.5,"EC90":7}'::jsonb, '{}'::jsonb, '{"ETL15":37.08,"ETL9":26.52,"ETL6":3.08,"5EL":14.27,"2EL":25.675,"3EL":114.55,"EC15":284.55,"EC90":34.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":43000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '28/4/2026', '2026-04-28T00:00:00.000Z', 'historical import',
  '{"ETL9":16,"5EL":20,"EC90":5}'::jsonb, '{"ETL15":0.8,"ETL9":8,"ETL6":1.08,"5EL":15.65,"2EL":8.375}'::jsonb, '{"ETL15":17.88,"ETL9":10.52,"ETL6":4.16,"5EL":28.92,"2EL":32.05,"3EL":109.05,"EC15":284.55,"EC90":27.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":54707,"Yellow":43000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '29/4/2026', '2026-04-29T00:00:00.000Z', 'historical import',
  '{"ETL9":5,"ETL6":5,"3EL":42}'::jsonb, '{"ETL9":14.2,"ETL6":22.08,"5EL":3.625,"2EL":10.775}'::jsonb, '{"ETL15":17.88,"ETL9":8.72,"ETL6":26.24,"5EL":12.545,"2EL":42.825,"3EL":109.05,"EC15":284.55,"EC90":22.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":51707,"Yellow":43000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '30/4/2026', '2026-04-30T00:00:00.000Z', 'historical import',
  '{"ETL9":25,"2EL":0.7,"3EL":7.85}'::jsonb, '{"ETL9":19.2,"ETL6":17.92,"5EL":1.5,"2EL":13.95}'::jsonb, '{"ETL15":57.88,"ETL9":22.92,"ETL6":39.16,"5EL":14.045,"2EL":56.775,"3EL":67.05,"EC15":284.55,"EC90":22.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":51707,"Yellow":41000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '1/5/2026', '2026-05-01T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":16.24,"2EL":32.85}'::jsonb, '{"ETL15":57.88,"ETL9":14.16,"ETL6":39.16,"5EL":14.045,"2EL":88.925,"3EL":59.2,"EC15":284.55,"EC90":22.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":51707,"Yellow":41000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '2/5/2026', '2026-05-02T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{}'::jsonb, '{"ETL15":57.88,"ETL9":14.16,"ETL6":39.16,"5EL":14.045,"2EL":88.925,"3EL":59.2,"EC15":284.55,"EC90":22.2,"Talk":547.175}'::jsonb, '{"kg25":{"Yellow":82000,"White":17500,"Beige":5500},"kg40":{"Beige":51707,"Yellow":41000,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '1/6/2026', '2026-06-01T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":20.56,"3EL":27}'::jsonb, '{"ETL15":51.6,"ETL9":172.68,"ETL6":3.76,"5EL":66.67,"2EL":45.775,"3EL":164.625,"EC15":271.9,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":58000,"White":12500,"Beige":3500},"kg40":{"Beige":38707,"Yellow":40500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '2/6/2026', '2026-06-02T00:00:00.000Z', 'historical import',
  '{"ETL15":0.6,"ETL9":17,"5EL":5,"3EL":20}'::jsonb, '{}'::jsonb, '{"ETL15":51.6,"ETL9":172.68,"ETL6":3.76,"5EL":66.67,"2EL":45.775,"3EL":164.625,"EC15":271.9,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":58000,"White":12500,"Beige":3500},"kg40":{"Beige":38707,"Yellow":40500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '3/6/2026', '2026-06-03T00:00:00.000Z', 'historical import',
  '{"ETL9":17,"3EL":11,"EC15":2.4}'::jsonb, '{"ETL9":31.92,"ETL6":21.2,"3EL":24.875}'::jsonb, '{"ETL15":51,"ETL9":187.6,"ETL6":24.96,"5EL":61.67,"2EL":45.775,"3EL":169.5,"EC15":271.9,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":58000,"White":12500,"Beige":3500},"kg40":{"Beige":38707,"Yellow":38500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '4/6/2026', '2026-06-04T00:00:00.000Z', 'historical import',
  '{"ETL9":13.48,"3EL":5,"EC15":3.5}'::jsonb, '{"ETL9":44.72,"3EL":40.275}'::jsonb, '{"ETL15":51,"ETL9":215.32,"ETL6":24.96,"5EL":61.67,"2EL":45.775,"3EL":198.775,"EC15":269.5,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":56000,"White":12500,"Beige":3500},"kg40":{"Beige":38707,"Yellow":38500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '5/6/2026', '2026-06-05T00:00:00.000Z', 'historical import',
  '{"ETL15":0.8,"ETL9":20,"ETL6":2,"3EL":0.5,"EC15":5.5}'::jsonb, '{"ETL9":39.52,"3EL":36.875}'::jsonb, '{"ETL15":51,"ETL9":241.36,"ETL6":24.96,"5EL":61.67,"2EL":45.775,"3EL":230.65,"EC15":266,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":54000,"White":12500,"Beige":3500},"kg40":{"Beige":36707,"Yellow":38500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '6/6/2026', '2026-06-06T00:00:00.000Z', 'historical import',
  '{"ETL9":31,"5EL":5,"2EL":0.5,"3EL":1.5,"EC15":1.5}'::jsonb, '{"ETL9":41.48,"3EL":36.375}'::jsonb, '{"ETL15":50.2,"ETL9":262.84,"ETL6":22.96,"5EL":61.67,"2EL":45.775,"3EL":266.525,"EC15":264,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":54000,"White":12500,"Beige":3500},"kg40":{"Beige":36707,"Yellow":38500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '7/6/2026', '2026-06-07T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":41.12,"3EL":33.875}'::jsonb, '{"ETL15":50.2,"ETL9":272.96,"ETL6":22.96,"5EL":56.67,"2EL":45.275,"3EL":298.9,"EC15":259,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":12500,"Beige":3500},"kg40":{"Beige":34707,"Yellow":38500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '8/6/2026', '2026-06-08T00:00:00.000Z', 'historical import',
  '{"ETL15":5,"ETL9":12,"3EL":7,"EC15":1.425,"Talk":5}'::jsonb, '{"ETL9":42.68,"2EL":24.375,"3EL":8.875}'::jsonb, '{"ETL15":50.2,"ETL9":315.64,"ETL6":22.96,"5EL":56.67,"2EL":69.65,"3EL":307.775,"EC15":259,"EC90":0,"Talk":542.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":12500,"Beige":3500},"kg40":{"Beige":34707,"Yellow":38500,"Green":2300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '9/6/2026', '2026-06-09T00:00:00.000Z', 'historical import',
  '{"ETL9":4,"3EL":4,"EC15":2}'::jsonb, '{"ETL9":48.48,"2EL":38.75}'::jsonb, '{"ETL15":45.2,"ETL9":352.12,"ETL6":22.96,"5EL":56.67,"2EL":108.4,"3EL":300.775,"EC15":257.575,"EC90":0,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":10500,"Beige":3500},"kg40":{"Beige":32707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '10/6/2026', '2026-06-10T00:00:00.000Z', 'historical import',
  '{"ETL9":24.6,"5EL":5,"EC15":0.2}'::jsonb, '{"ETL9":29.6,"2EL":25.25}'::jsonb, '{"ETL15":45.2,"ETL9":377.72,"ETL6":22.96,"5EL":56.67,"2EL":133.65,"3EL":296.775,"EC15":255.575,"EC90":0,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":8500,"Beige":3500},"kg40":{"Beige":30707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '11/6/2026', '2026-06-11T00:00:00.000Z', 'historical import',
  '{"ETL9":21,"ETL6":5,"3EL":7}'::jsonb, '{"ETL9":30,"2EL":31.5,"EC15":1.25,"EC90":2.48}'::jsonb, '{"ETL15":45.2,"ETL9":383.12,"ETL6":22.96,"5EL":51.67,"2EL":165.15,"3EL":296.775,"EC15":256.625,"EC90":2.48,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":6500,"Beige":3000},"kg40":{"Beige":30707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '12/6/2026', '2026-06-12T00:00:00.000Z', 'historical import',
  '{"ETL15":0.04,"ETL9":31,"2EL":5,"3EL":16.15}'::jsonb, '{"ETL9":0.88,"2EL":30.55,"EC15":1.25,"EC90":24.64}'::jsonb, '{"ETL15":45.2,"ETL9":363,"ETL6":17.96,"5EL":51.67,"2EL":195.7,"3EL":289.775,"EC15":257.875,"EC90":27.12,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":6500,"Beige":3000},"kg40":{"Beige":30707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '13/6/2026', '2026-06-13T00:00:00.000Z', 'historical import',
  '{"ETL9":12.52,"2EL":20,"3EL":63}'::jsonb, '{"2EL":36.125,"EC90":40.24}'::jsonb, '{"ETL15":45.16,"ETL9":332,"ETL6":17.96,"5EL":51.67,"2EL":226.825,"3EL":273.625,"EC15":257.875,"EC90":67.36,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":4500,"Beige":3000},"kg40":{"Beige":28707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '14/6/2026', '2026-06-14T00:00:00.000Z', 'historical import',
  '{"2EL":20}'::jsonb, '{"2EL":34.375,"EC90":42.6}'::jsonb, '{"ETL15":45.16,"ETL9":319.48,"ETL6":17.96,"5EL":51.67,"2EL":241.2,"3EL":210.625,"EC15":257.875,"EC90":109.96,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":2500,"Beige":3000},"kg40":{"Beige":28707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '15/6/2026', '2026-06-15T00:00:00.000Z', 'historical import',
  '{"ETL9":16.2,"ETL6":1,"5EL":10,"2EL":25,"3EL":7,"EC15":0.8,"EC90":10}'::jsonb, '{"2EL":40,"EC90":44.8}'::jsonb, '{"ETL15":45.16,"ETL9":319.48,"ETL6":17.96,"5EL":51.67,"2EL":261.2,"3EL":210.625,"EC15":257.875,"EC90":154.76,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":2500,"Beige":3000},"kg40":{"Beige":28707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '16/6/2026', '2026-06-16T00:00:00.000Z', 'historical import',
  '{"ETL15":40,"ETL9":30,"2EL":5}'::jsonb, '{"2EL":35.75,"EC90":46.6}'::jsonb, '{"ETL15":45.16,"ETL9":303.28,"ETL6":16.96,"5EL":41.67,"2EL":271.2,"3EL":203.625,"EC15":257.075,"EC90":191.36,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":1000,"Beige":3000},"kg40":{"Beige":26707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '17/6/2026', '2026-06-17T00:00:00.000Z', 'historical import',
  '{"ETL15":2,"ETL9":29,"5EL":5,"2EL":25,"3EL":27,"EC90":4}'::jsonb, '{"ETL9":41.84,"5EL":35.5,"2EL":15.925,"EC15":2,"EC90":6.32}'::jsonb, '{"ETL15":5.16,"ETL9":315.12,"ETL6":16.96,"5EL":77.17,"2EL":282.875,"3EL":203.625,"EC15":259.075,"EC90":197.68,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":1000,"Beige":0},"kg40":{"Beige":24707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '18/6/2026', '2026-06-18T00:00:00.000Z', 'historical import',
  '{"ETL9":38.96,"2EL":30,"3EL":11,"EC90":1}'::jsonb, '{"ETL9":16.68,"5EL":24.5}'::jsonb, '{"ETL15":3.16,"ETL9":302.8,"ETL6":16.96,"5EL":96.67,"2EL":257.875,"3EL":176.625,"EC15":259.075,"EC90":193.68,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":1000,"Beige":0},"kg40":{"Beige":24707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '19/6/2026', '2026-06-19T00:00:00.000Z', 'historical import',
  '{"ETL9":33.92,"ETL6":5,"5EL":15,"2EL":40,"3EL":1.15,"EC90":1.68}'::jsonb, '{"ETL9":47.8,"5EL":24.95,"3EL":22.25}'::jsonb, '{"ETL15":3.16,"ETL9":311.64,"ETL6":16.96,"5EL":121.62,"2EL":227.875,"3EL":187.875,"EC15":258.075,"EC90":193.68,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":51000,"White":1000,"Beige":0},"kg40":{"Beige":24707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '20/6/2026', '2026-06-20T00:00:00.000Z', 'historical import',
  '{"ETL9":40.4,"ETL6":1,"2EL":5,"3EL":32}'::jsonb, '{"ETL9":46,"ETL6":20,"3EL":34.05}'::jsonb, '{"ETL15":3.16,"ETL9":323.72,"ETL6":31.96,"5EL":106.62,"2EL":187.875,"3EL":220.775,"EC15":258.075,"EC90":192,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":48000,"White":1000,"Beige":0},"kg40":{"Beige":24707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '21/6/2026', '2026-06-21T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":50.84,"ETL6":25,"3EL":31}'::jsonb, '{"ETL15":3.16,"ETL9":334.16,"ETL6":55.96,"5EL":106.62,"2EL":182.875,"3EL":219.775,"EC15":258.075,"EC90":192,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":48000,"White":1000,"Beige":0},"kg40":{"Beige":22707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '22/6/2026', '2026-06-22T00:00:00.000Z', 'historical import',
  '{"ETL9":41.8,"5EL":2.5,"2EL":5,"EC90":3,"Talk":3.4}'::jsonb, '{"ETL9":47.96,"ETL6":20,"3EL":32.5}'::jsonb, '{"ETL15":5.16,"ETL9":382.12,"ETL6":75.96,"5EL":106.62,"2EL":182.875,"3EL":252.275,"EC15":258.075,"EC90":192,"Talk":537.175}'::jsonb, '{"kg25":{"Yellow":48000,"White":1000,"Beige":0},"kg40":{"Beige":22707,"Yellow":38500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '23/6/2026', '2026-06-23T00:00:00.000Z', 'historical import',
  '{"ETL9":5.52,"2EL":20,"3EL":106.15,"EC90":1}'::jsonb, '{"ETL9":40.24,"ETL6":20,"3EL":36}'::jsonb, '{"ETL15":3.16,"ETL9":380.56,"ETL6":95.96,"5EL":104.12,"2EL":177.875,"3EL":288.275,"EC15":258.075,"EC90":189,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":46000,"White":1000,"Beige":0},"kg40":{"Beige":20707,"Yellow":37500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '24/6/2026', '2026-06-24T00:00:00.000Z', 'historical import',
  '{"ETL15":10,"ETL9":37,"5EL":0.5,"2EL":27.5,"3EL":0.5,"EC15":5,"EC90":5}'::jsonb, '{"ETL9":50.8,"3EL":46}'::jsonb, '{"ETL15":3.16,"ETL9":425.84,"ETL6":95.96,"5EL":104.12,"2EL":157.875,"3EL":228.125,"EC15":258.075,"EC90":188,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":44000,"White":1000,"Beige":0},"kg40":{"Beige":18707,"Yellow":37500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '25/6/2026', '2026-06-25T00:00:00.000Z', 'historical import',
  '{"ETL15":3,"ETL9":25,"3EL":5,"EC15":5}'::jsonb, '{"ETL15":10,"ETL9":51,"ETL6":1.6,"3EL":23.5}'::jsonb, '{"ETL15":3.16,"ETL9":439.84,"ETL6":97.56,"5EL":103.62,"2EL":130.375,"3EL":251.125,"EC15":253.075,"EC90":183,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":42000,"White":1000,"Beige":0},"kg40":{"Beige":18707,"Yellow":36500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '26/6/2026', '2026-06-26T00:00:00.000Z', 'historical import',
  '{"ETL9":11.32,"2EL":5,"3EL":15,"EC90":6}'::jsonb, '{"ETL9":25.48}'::jsonb, '{"ETL15":0.16,"ETL9":440.32,"ETL6":97.56,"5EL":103.62,"2EL":130.375,"3EL":246.125,"EC15":248.075,"EC90":183,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":42000,"White":1000,"Beige":0},"kg40":{"Beige":16707,"Yellow":36500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '27/6/2026', '2026-06-27T00:00:00.000Z', 'historical import',
  '{"ETL15":1,"ETL9":25,"3EL":1.15,"EC90":1}'::jsonb, '{"ETL15":13.6,"ETL9":12.4}'::jsonb, '{"ETL15":13.76,"ETL9":441.4,"ETL6":97.56,"5EL":103.62,"2EL":125.375,"3EL":231.125,"EC15":248.075,"EC90":177,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":42000,"White":1000,"Beige":0},"kg40":{"Beige":16707,"Yellow":36500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '28/6/2026', '2026-06-28T00:00:00.000Z', 'historical import',
  '{"ETL9":10}'::jsonb, '{"ETL15":40.4,"ETL9":12.8}'::jsonb, '{"ETL15":53.16,"ETL9":429.2,"ETL6":97.56,"5EL":103.62,"2EL":125.375,"3EL":229.975,"EC15":248.075,"EC90":176,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":42000,"White":1000,"Beige":0},"kg40":{"Beige":16707,"Yellow":34500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '29/6/2026', '2026-06-29T00:00:00.000Z', 'historical import',
  '{"ETL9":44,"EC90":1}'::jsonb, '{"ETL15":30.4,"ETL9":3.8}'::jsonb, '{"ETL15":83.56,"ETL9":423,"ETL6":97.56,"5EL":103.62,"2EL":125.375,"3EL":229.975,"EC15":248.075,"EC90":176,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":42000,"White":1000,"Beige":0},"kg40":{"Beige":16707,"Yellow":34500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '30/6/2026', '2026-06-30T00:00:00.000Z', 'historical import',
  '{"ETL9":15,"EC15":2}'::jsonb, '{"ETL15":12.8,"ETL9":28.4,"3EL":20.175}'::jsonb, '{"ETL15":96.36,"ETL9":407.4,"ETL6":97.56,"5EL":103.62,"2EL":125.375,"3EL":250.15,"EC15":248.075,"EC90":175,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":41000,"White":1000,"Beige":0},"kg40":{"Beige":14707,"Yellow":34500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

insert into daily_ops_reports (date_label, date, reported_by, delivered, received, stock, bags, raw_text, source) values (
  '1/7/2026', '2026-07-01T00:00:00.000Z', 'historical import',
  '{}'::jsonb, '{"ETL9":57.2,"3EL":37}'::jsonb, '{"ETL15":96.36,"ETL9":449.6,"ETL6":97.56,"5EL":103.62,"2EL":125.375,"3EL":287.15,"EC15":246.075,"EC90":175,"Talk":533.775}'::jsonb, '{"kg25":{"Yellow":41000,"White":1000,"Beige":0},"kg40":{"Beige":14707,"Yellow":34500,"Green":300}}'::jsonb,
  null, 'app'
) on conflict (date_label) do update set
  delivered = daily_ops_reports.delivered || excluded.delivered,
  received  = daily_ops_reports.received  || excluded.received,
  stock     = daily_ops_reports.stock     || excluded.stock,
  bags = jsonb_build_object(
    'kg25', coalesce(daily_ops_reports.bags -> 'kg25', '{}'::jsonb) || coalesce(excluded.bags -> 'kg25', '{}'::jsonb),
    'kg40', coalesce(daily_ops_reports.bags -> 'kg40', '{}'::jsonb) || coalesce(excluded.bags -> 'kg40', '{}'::jsonb)
  ),
  updated_at = now();

commit;

-- Expect: select count(*) from daily_ops_reports;  -->  62
