-- MinTech Ethiopia — daily production reports, Aug 2026.
-- GENERATED by scripts/generate-production-seed.mjs from
-- scripts/august-2026-production.csv — do not edit by hand.
--
-- 31 days, 1818.235 t in total, products: ETL9, 2EL, 3EL, 5EL, EC15, EC90.
-- Every row's cells were checked against the sheet's own Total column before
-- this file was written; a single disagreement would have aborted it.
--
-- Paste into the Supabase SQL editor and Run. SAFE TO RE-RUN: the delete below
-- clears only rows this import wrote (reported_by = 'historical import')
-- within the month, so anything filed through the bot for those days is left
-- exactly as it is. Run it twice and you still have one copy of each day.
--
-- The dates are stored at UTC midnight, which is what the guided production
-- flow writes when somebody picks a day in the calendar.

begin;

delete from production_reports
 where date >= '2026-08-01T00:00:00.000Z' and date < '2026-09-01T00:00:00.000Z'
   and reported_by = 'historical import';

insert into production_reports (date, fgr_no, reported_by, products, source) values
  -- 1-Aug · 80.75 t
  ('2026-08-01T00:00:00.000Z', '9583', 'historical import', '{"ETL9":41,"2EL":39.75}'::jsonb, 'app'),
  -- 2-Aug · 81.215 t
  ('2026-08-02T00:00:00.000Z', '9584', 'historical import', '{"ETL9":50.64,"2EL":30.575}'::jsonb, 'app'),
  -- 3-Aug · 86.465 t
  ('2026-08-03T00:00:00.000Z', '9585', 'historical import', '{"ETL9":59.24,"2EL":27.225}'::jsonb, 'app'),
  -- 4-Aug · 72.725 t
  ('2026-08-04T00:00:00.000Z', '9586', 'historical import', '{"ETL9":51.6,"2EL":21.125}'::jsonb, 'app'),
  -- 5-Aug · 65.15 t
  ('2026-08-05T00:00:00.000Z', '9587', 'historical import', '{"ETL9":41.8,"2EL":23.35}'::jsonb, 'app'),
  -- 6-Aug · 57.445 t
  ('2026-08-06T00:00:00.000Z', '9588', 'historical import', '{"ETL9":31.32,"2EL":26.125}'::jsonb, 'app'),
  -- 7-Aug · 92.15 t
  ('2026-08-07T00:00:00.000Z', '9589', 'historical import', '{"ETL9":50.4,"2EL":41.75}'::jsonb, 'app'),
  -- 8-Aug · 93.14 t
  ('2026-08-08T00:00:00.000Z', '9590', 'historical import', '{"ETL9":51.64,"2EL":41.5}'::jsonb, 'app'),
  -- 9-Aug · 54.015 t
  ('2026-08-09T00:00:00.000Z', '9591', 'historical import', '{"ETL9":23.24,"2EL":30.775}'::jsonb, 'app'),
  -- 10-Aug · 65.475 t
  ('2026-08-10T00:00:00.000Z', '9592', 'historical import', '{"ETL9":36.4,"2EL":29.075}'::jsonb, 'app'),
  -- 11-Aug · 65.07 t
  ('2026-08-11T00:00:00.000Z', '9593', 'historical import', '{"ETL9":38.92,"3EL":24.375,"2EL":1.775}'::jsonb, 'app'),
  -- 12-Aug · 53.215 t
  ('2026-08-12T00:00:00.000Z', '9594', 'historical import', '{"ETL9":23.04,"3EL":30.175}'::jsonb, 'app'),
  -- 13-Aug · 66.86 t
  ('2026-08-13T00:00:00.000Z', '9595', 'historical import', '{"ETL9":37.56,"3EL":29.3}'::jsonb, 'app'),
  -- 14-Aug · 56.64 t
  ('2026-08-14T00:00:00.000Z', '9596', 'historical import', '{"ETL9":26.64,"3EL":30}'::jsonb, 'app'),
  -- 15-Aug · 66.315 t
  ('2026-08-15T00:00:00.000Z', '9597', 'historical import', '{"ETL9":26.84,"3EL":39.475}'::jsonb, 'app'),
  -- 16-Aug · 37.46 t
  ('2026-08-16T00:00:00.000Z', '9598', 'historical import', '{"ETL9":17.76,"3EL":19.7}'::jsonb, 'app'),
  -- 17-Aug · 78.245 t
  ('2026-08-17T00:00:00.000Z', '9599', 'historical import', '{"ETL9":45.72,"3EL":32.525}'::jsonb, 'app'),
  -- 18-Aug · 58.47 t
  ('2026-08-18T00:00:00.000Z', '9600', 'historical import', '{"ETL9":28.12,"3EL":30.35}'::jsonb, 'app'),
  -- 19-Aug · 84.625 t
  ('2026-08-19T00:00:00.000Z', '9601', 'historical import', '{"ETL9":38.2,"5EL":46.25,"3EL":0.175}'::jsonb, 'app'),
  -- 20-Aug · 91.385 t
  ('2026-08-20T00:00:00.000Z', '9602', 'historical import', '{"ETL9":34.76,"5EL":56.625}'::jsonb, 'app'),
  -- 21-Aug · 81.585 t
  ('2026-08-21T00:00:00.000Z', '9603', 'historical import', '{"ETL9":34.96,"5EL":46.625}'::jsonb, 'app'),
  -- 22-Aug · 50.905 t
  ('2026-08-22T00:00:00.000Z', '9521 / 9604', 'historical import', '{"ETL9":1.48,"5EL":43,"EC15":6.425}'::jsonb, 'app'),
  -- 23-Aug · 74.62 t
  ('2026-08-23T00:00:00.000Z', '9522 / 9605', 'historical import', '{"5EL":35.5,"EC90":39.12}'::jsonb, 'app'),
  -- 24-Aug · 57.115 t
  ('2026-08-24T00:00:00.000Z', '9523 / 9606', 'historical import', '{"2EL":34.075,"EC90":23.04}'::jsonb, 'app'),
  -- 25-Aug · 22.115 t
  ('2026-08-25T00:00:00.000Z', '9524 / 9607', 'historical import', '{"2EL":15.675,"EC90":6.44}'::jsonb, 'app'),
  -- 26-Aug · 30.92 t
  ('2026-08-26T00:00:00.000Z', '9525 / 9608', 'historical import', '{"2EL":21.2,"EC90":9.72}'::jsonb, 'app'),
  -- 27-Aug · 0 t
  ('2026-08-27T00:00:00.000Z', null, 'historical import', '{}'::jsonb, 'app'),
  -- 28-Aug · 11.6 t
  ('2026-08-28T00:00:00.000Z', '9526 / 9609', 'historical import', '{"2EL":8,"EC90":3.6}'::jsonb, 'app'),
  -- 29-Aug · 30 t
  ('2026-08-29T00:00:00.000Z', '9527 / 9610', 'historical import', '{"2EL":20,"EC90":10}'::jsonb, 'app'),
  -- 30-Aug · 24.85 t
  ('2026-08-30T00:00:00.000Z', '9528 / 9611', 'historical import', '{"2EL":16.45,"EC90":8.4}'::jsonb, 'app'),
  -- 31-Aug · 27.71 t
  ('2026-08-31T00:00:00.000Z', '9529 / 9612', 'historical import', '{"2EL":18.75,"EC90":8.96}'::jsonb, 'app');

commit;

-- Expect: 31 days, 1818.235 t.
select count(*) as days,
       round(sum((select coalesce(sum(value::numeric), 0) from jsonb_each_text(products))), 3) as tonnes
  from production_reports
 where date >= '2026-08-01T00:00:00.000Z' and date < '2026-09-01T00:00:00.000Z'
   and reported_by = 'historical import';
