-- MinTech Ethiopia — the store's OPENING COUNT.
-- GENERATED by scripts/generate-store-seed.mjs from
-- scripts/store-opening-count.csv — do not edit by hand.
--
-- 29 items across 5 groups, from 32 sheet rows: items listed
-- twice (they left on two vouchers) are summed into the one pile they are.
--
-- This is what is on the shelf TODAY. Every count filed from the bot after it
-- supersedes these figures item by item, exactly as one count supersedes
-- another — nothing here is special except that it came first.
--
-- Paste into the Supabase SQL editor and Run. SAFE TO RE-RUN: the delete below
-- clears only the row this seed wrote (counted_by = 'opening count'), so a
-- count filed from the bot is never touched.
--
--   10A                           1   ref 8554  techni
--   32A                           1   ref 8561  techni
--   40A                           1   ref 8568  techni
--   50A                           1   ref 8554  techni
--   plastic broom                 2   ref 8567  produc
--   China electrod #3.2           4   ref 8555  techni
--   Epoxy                         2   ref 8558  techni
--   Greas Nipple                  2   ref 8558  techni
--   Hammer 6kg                    2   ref 8567  produc
--   Lather vglove                32   ref 8560  produc
--   Mop                           1   ref 8567  produc
--   Round bar #25                 1   ref 8559  techni
--   Sewing theared              125   ref 8560/8567  produc
--   silcone sealant               1   ref 8554  techni
--   Electric cable #2.5           1   ref 8553  w/Sho
--   Cable lag #25                 3   ref 8561  techni
--   Cable lag #35                 6   ref 8561  techni
--   Capaciter                     2   ref 8568  techni
--   conduet                      13   ref 8553  w/Sho
--   Lamp                          4   ref 8553  w/Sho
--   Lamp holder                   3   ref 8553  w/Sho
--   Led 18W                       2   ref 8553  w/Sho
--   Limite swich                  2   ref 8554/8568  techni
--   On Off swich                  4   ref 8553  w/Sho
--   socket                        1   ref 8561  techni
--   Cutting disck 180*1.6*22     15   ref 8555/8558  techni
--   Cutting disck 230*2*22.2      5   ref 8555  techni
--   Square bar 10*10*6m           1   ref 8559  techni
--   Square bar 30*30*6m           3   ref 8559  techni

begin;

delete from store_counts where counted_by = 'opening count';

insert into store_counts (date, date_label, groups, items, counted_by, source)
values (
  '2026-10-02T00:00:00.000Z',
  '2026-10-02',
  '{brk,con,cons,elec2,wsh}',
  '{"elec2:led-18w":2,"elec2:lamp":4,"elec2:lamp-holder":3,"elec2:cable-2.5":1,"elec2:on-off-switch":4,"elec2:conduit":13,"con:50A":1,"brk:10A":1,"elec2:limit-switch":2,"cons:silicone":1,"cons:china-electrod-3.2":4,"wsh:cut-180x1.6x22":15,"wsh:cut-230x2x22.2":5,"cons:epoxy":2,"cons:grease-nipple":2,"wsh:sqbar-30":3,"wsh:sqbar-10":1,"cons:rbar-25":1,"cons:sewing-thread":125,"cons:leather-glove":32,"elec2:cable-lag-35":6,"elec2:socket":1,"con:32A":1,"elec2:cable-lag-25":3,"cons:hammer-6kg":2,"cons:broom":2,"cons:mop":1,"elec2:capacitor":2,"con:40A":1}'::jsonb,
  'opening count',
  'app'
);

commit;

-- Expect: one row, 29 items.
select date_label, counted_by, groups,
       (select count(*) from jsonb_object_keys(items)) as items
  from store_counts
 where counted_by = 'opening count';
